### ISSUE TITLE
Loading the extension removes icons

### ISSUE THREAD

**Issue by DarkGhostHunter** [celiopy/auto-adwaita-colors#1]
Installed the extension (v5) and the icons are all _messed up_. I guess it's showing the default icons instead of the adwaita ones.

![image](https://github.com/user-attachments/assets/107012bd-bb42-46e5-b6f1-4ee30a5f383a)

GNOME 47, Bluefin DX Stable (Fedora Silverblue 41).

**Comment by celiopy** [comment]
Yeah, that's because you need Adwaita-colors for it to work, clicking "Download" in extension's settings will do this for you. Sadly I can not make the extension download it without user consent.

**Comment by DarkGhostHunter** [comment]
> clicking "Download" in extension's settings will do this for you

There are no settings, hence no Download button.

**Comment by celiopy** [comment]
Sorry, didn't express correctly, I mean that it will, but for the version that is active on Gnome Extensions, you must get the icons from [https://github.com/dpejoh/Adwaita-colors](here).

**Comment by DarkGhostHunter** [comment]
Got it. Had to install it into `/var/usrlocal/share` since i'm on a immutable distro.
