### ISSUE TITLE
Mild incompatibility with MoreWaita

### ISSUE THREAD

**Issue by EPOCHvoyager** [celiopy/auto-adwaita-colors#5]
When selecting the default accent color, the icon theme will revert back to stock Adwaita, which will of course be missing the MoreWaita icons when compared to the MoreWaita-integrated Adwaita-colors themes. I could suggest adding a check for a MoreWaita installation and automatically changing icon theme to it when the default blue is selected, perhaps with a setting toggle.

Nonetheless, thanks for your work on this extension!

**Comment by celiopy** [comment]
Hey, thank you for using it!

By default, Adwaita-colors just inherits Adwaita, you could check [Adwaita-colors MoreWaita script](https://github.com/dpejoh/Adwaita-colors/blob/main/MoreWaita.sh), it can be found at $HOME/.local/share/icons if you've downloaded within the extension. I can maybe configure it to automatically run when the user downloads/updates within the extension, in a next release.

**Comment by celiopy** [comment]
New release address this issue. Now if the user have MoreWaita installed it automatically runs `MoreWaita.sh` from Adwaita-colors!
